### PR TITLE
Add rails < 4.1 support

### PR DESCRIPTION
**Pull request by betesh**
This is passing on travis

### CODE REVIEW

**Comment by nerde** [comment]
Thanks @betesh!

**Comment by betesh** [comment]
Can I trouble you to push a new gem?

**Comment by nerde** [comment]
Sure. I'll publish it soon. I'm having a problem with dependencies though. My rake tasks are not working. I'll publish as soon as I get it fixed.

**Comment by nerde** [comment]
Done. :)

**Pull request merged**
